<?php
/**
 * userguide.php — MARS APRS Map
 *
 * Serves the pre-rendered user guide with an optional back link.
 * Accepts ?back=<url> to set the return link.
 * Content is generated by make-docs-html.py → userguide-body.html.
 *
 * ©2025 Doug Kaye, K6DRK <doug@rds.com>
 */
$back      = !empty($_GET['back']) ? $_GET['back'] : '/';
$backLabel = ($back === '/') ? '← Return to Map' : '← Back';
$backHref  = htmlspecialchars($back, ENT_QUOTES);
$backText  = htmlspecialchars($backLabel, ENT_QUOTES);
$body      = file_get_contents(__DIR__ . '/userguide-body.html');
if ($body === false) { $body = '<p style="color:red">User guide not available.</p>'; }
?><!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>MARS APRS — User Guide</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }

  body {
    font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Arial, sans-serif;
    font-size: 14px;
    line-height: 1.5;
    color: #222;
    background: #f5f5f5;
  }

  header {
    background: #444;
    color: #fff;
    padding: 14px 24px;
    display: flex;
    align-items: center;
    gap: 16px;
  }

  header h1 {
    font-size: 1.1rem;
    font-weight: 600;
    letter-spacing: 0.01em;
  }

  header a {
    color: #ccc;
    text-decoration: none;
    font-size: 0.9rem;
    margin-left: auto;
    white-space: nowrap;
  }

  header a:hover { color: #fff; }

  #content {
    max-width: 820px;
    margin: 20px auto 40px;
    background: #fff;
    border: 1px solid #ddd;
    border-radius: 6px;
    padding: 24px 40px;
  }

  #content h1 {
    font-size: 1.7rem;
    font-weight: 700;
    margin-bottom: 6px;
    padding-bottom: 12px;
    border-bottom: 2px solid #ddd;
    margin-top: 24px;
  }

  #content h1:first-child { margin-top: 0; }

  #content h2 {
    font-size: 1.2rem;
    font-weight: 700;
    margin-top: 28px;
    margin-bottom: 8px;
    padding-bottom: 5px;
    border-bottom: 1px solid #e0e0e0;
  }

  #content h3 {
    font-size: 1rem;
    font-weight: 700;
    margin-top: 18px;
    margin-bottom: 6px;
    color: #333;
  }

  #content h4 {
    font-size: 0.92rem;
    font-weight: 700;
    margin-top: 14px;
    margin-bottom: 5px;
    color: #444;
  }

  #content p { margin-bottom: 8px; }

  #content ul, #content ol {
    margin: 4px 0 10px 22px;
  }

  #content li { margin-bottom: 3px; }

  #content li > p { margin-bottom: 3px; }

  #content strong { font-weight: 700; }

  #content em { font-style: italic; }

  #content code {
    font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace;
    font-size: 0.88em;
    background: #f0f0f0;
    border: 1px solid #ddd;
    border-radius: 3px;
    padding: 1px 5px;
  }

  #content pre {
    background: #f0f0f0;
    border: 1px solid #ddd;
    border-radius: 4px;
    padding: 14px 16px;
    overflow-x: auto;
    margin: 10px 0 16px;
    font-size: 0.88em;
    line-height: 1.5;
  }

  #content pre code {
    background: none;
    border: none;
    padding: 0;
  }

  #content table {
    border-collapse: collapse;
    width: 100%;
    margin: 8px 0 12px;
    font-size: 0.9em;
  }

  #content th {
    background: #444;
    color: #fff;
    text-align: left;
    padding: 5px 10px;
    font-weight: 600;
  }

  #content td {
    padding: 4px 10px;
    border-bottom: 1px solid #e0e0e0;
    vertical-align: top;
  }

  #content tr:nth-child(even) td { background: #fafafa; }

  #content hr {
    border: none;
    border-top: 1px solid #e0e0e0;
    margin: 16px 0;
  }

  #content a { color: #0969da; text-decoration: none; }
  #content a:hover { text-decoration: underline; }

  @media (max-width: 680px) {
    #content { padding: 24px 18px; margin: 16px 8px 40px; }
    header { padding: 12px 16px; }
  }

  @media print {
    header { display: none; }
    body { background: #fff; font-size: 12px; }
    #content {
      margin: 0;
      border: none;
      border-radius: 0;
      padding: 0;
      max-width: 100%;
    }
    pre {
      break-inside: avoid;
      page-break-inside: avoid;
    }
    h2, h3, h4 {
      break-after: avoid;
      page-break-after: avoid;
    }
  }
</style>
</head>
<body>

<header>
  <h1>MARS APRS — User Guide</h1>
  <a href="<?= $backHref ?>"><?= $backText ?></a>
</header>

<div id="content">
<?= $body ?>
</div>

</body>
</html>
